# achievements_config.py

ACHIEVEMENTS = {
    # ── 通常実績・追加実績 ──
    "not_admin": {"name": "あなたは管理者じゃないでしょ？", "description": "鯖内で表示される名前を「ぴくせる」にして「ストゼロ」を含むメッセージを発言する。", "is_hidden": False},
    "buy_anger": {"name": "怒りを買うよ？", "description": "「ぽこでん」と発言する。", "is_hidden": False},
    "private_life_manager": {"name": "私生活管理者", "description": "「ピコハン」と「ぴくせる」を含む発言をする。", "is_hidden": False},
    "osoyou": {"name": "おそよう","description": "お昼を過ぎた13時以降におはようと発言する。","is_hidden": False},
    "staple_is_mic": {"name": "主食はマイク", "description": "累計VC接続時間24時間に達する。", "is_hidden": False},
    "trash_talk": {"name": "ぽい捨てするなよ？", "description": "@ばうむをめんしょんする。", "is_hidden": False},
    "noisy": {"name": "うるさい", "description": "#が文頭に入っていて15字以上のメッセージの発言をする。", "is_hidden": False},
    "sake_addict": {"name": "酒カス", "description": "最初の発言から3分以内に酒に関する発言を2個する。", "is_hidden": False},
    "energy_addict": {"name": "エナカス", "description": "最初の発言から3分以内にエンドリに関する発言を2個する。", "is_hidden": False},
    "no_alcohol_ii": {"name": "アルハラすんなよ！！！", "description": "22時以降に酒関連の発言をする。", "is_hidden": False},
    "genki": {"name": "げんき！！！！", "description": "「わんだほい」と発言する。", "is_hidden": False},
    "cold_laugh": {"name": "...w", "description": "冷笑する。", "is_hidden": False},
    "moyashi": {"name": "もやし", "description": "文章中に1を含めた発言をする。", "is_hidden": False},
    "hage": {"name": "はげちゃうわ", "description": "「はげ」を含める発言する。", "is_hidden": False},
    "stalker": {"name": "ストーカー", "description": "同じ人返信又はリアクションを24時間以内に合計10回する。", "is_hidden": False},
    "not_twilight": {"name": "ここは黄昏ではありません", "description": "暴走ch以外でえらこほりたいと発言する。", "is_hidden": False},
    "typing_no_need": {"name": "文字起こし不要？", "description": "24時間以内に100メッセージ送信する。", "is_hidden": False},
    "spam_king": {"name": "連投王", "description": "連続で5通のメッセージを送信する。", "is_hidden": False},
    "midnight_talker": {"name": "深夜の語り部", "description": "深夜0時以降〜朝4時にVCへ参加する。", "is_hidden": False},
    "empathy_storm": {"name": "共感の嵐", "description": "他のメンバーのメッセージにリアクション50回をつける。", "is_hidden": False},
    "emoji_artisan": {"name": "絵文字職人", "description": "サーバーのカスタム絵文字を累計100使う。", "is_hidden": False},
    "bot_best_friend": {"name": "botの親友", "description": "botに対してコマンドを20回実行する。", "is_hidden": False},
    "night_owl": {"name": "夜更かしの民", "description": "深夜2時～朝4時の間にメッセージを送信する。", "is_hidden": False},
    "silent_supporter": {"name": "サイレントサポーター", "description": "ミュートのまま1時間VCに接続する。", "is_hidden": False},
    "typo": {"name": "誤字ですよ", "description": "1分以内に2回自分のメッセージを編集する。", "is_hidden": False},
    
    # 画像追加分の実績
    "among_us": {"name": "アモアスですか？", "description": "「人狼」と言う", "is_hidden": False},
    "sound_gamer": {"name": "貴様ッ…音ゲーマーだなっ！！", "description": "「ゴママヨ」と言う", "is_hidden": False},
    "mention_fail": {"name": "メンション失敗（笑）", "description": "「@ユーザー名」というメンションになっていないものを送信する", "is_hidden": False},
    "wrong_channel": {"name": "淫夢チャンネルはここではないですよ！早く気づいて！", "description": "「やりますねぇ」と暴走機関車聞き専以外で言う", "is_hidden": False},
    "playback_fail": {"name": "再生できてませんよ", "description": "VCに入っていない状態で「m!p https://」と言う", "is_hidden": False},
    "midnight_monologue": {"name": "深夜の独り言","description": "サーバー内の誰とも会話が重なっていない状態で、1時間以上を空けて誰もいないチャンネルにぽつんとメッセージを投稿する。","is_hidden": False},
    "you_free": {"name": "あなた暇なの？", "description": "VCに24時間入る", "is_hidden": False},
    
    # チャンネル指定系
    "zatsudan_1": {"name": "れっつざつだん！", "description": "ざつだん1で発言する", "is_hidden": False},
    "vomit": {"name": "辛いことは全部吐き出して", "description": "愚痴・発狂で発言する", "is_hidden": False},
    "twitter_faction": {"name": "Twitter派だよね？", "description": "X宣伝で発言する", "is_hidden": False},
    
    "shining": {"name": "光ってる？", "description": "「ぴくせる」と言う", "is_hidden": False},
    "bad_words": {"name": "悪口はダメですよ？", "description": "「バカ」「クソ」「カス」のどれかを言う（かな・漢字・ローマ字対応）", "is_hidden": False},
    "shiritori": {"name": "り……隣人！", "description": "「しりとり」と言う", "is_hidden": False},
    "dice_madness": {"name": "そんなダイス使わんやろ", "description": "100d100000と打つ", "is_hidden": False},
    # Ver.2実装実績
    "secretive": {"name": "秘密主義", "description": "スポイラーを使用した発言をする。"},
    "shadow_shadow": {"name": "Shadow Shadow", "description": "「孤独」を発言する。"},
    "mezumizer": {"name": "メズマイライザー", "description": "「誰か助けてね」と発言する。"},
    "absolute_justice": {"name": "絶対ジャスティス！", "description": "「引きこもり」と発言する。"},
    "what_was_i": {"name": "あたしってなんごっけ", "description": "「わからない」と発言する。"},
    "fossil": {"name": "取り繕っていたいな", "description": "「化石」と発言する。"},
    "i_know_nothing": {"name": "僕は何も知らない", "description": "「知らない」と発言する。"},
    "rebellion_god": {"name": "神への反逆", "description": "実績botに対して返信する。"},
    "tamaya": {"name": "たーまやー", "description": "「爆死」を含む発言をする。"},
    "anta_baka": {"name": "あんたばかぁ？", "description": "ユーザーがユーザー自身をメンションする。"},
    "self_intro_first": {"name": "まずは事故紹介から", "description": "事故紹介chで発言する。"},
    "good_night": {"name": "Good night", "description": "21-2時の間に「おやすみ」と発言する。"},
    "seichi": {"name": "整地してくるわ", "description": "「マイクラ」、「マインクラフト」を含む発言をする。（英語も可）"},
    "not_sleepy": {"name": "眠くないの？", "description": "深夜4時-6時の間に「おはよう」と発言する。"},
    "hanshin": {"name": "なんでや！阪神関係ないやろ！", "description": "「33-4」または「334」を含む発言をする。"},
    "saba_no_inochi": {"name": "鯖主の命", "description": "「ストゼロ」「ストロングゼロ」を発言する。"},
    "reach": {"name": "R'E'A'C'H'", "description": "「お手を拝借」と発言する。"},
    "past_mistake": {"name": "消えぬ過ち", "description": "「じろりんぐ」「ziroring」を発言する。"},
    "rariat_no_ne_yo": {"name": "らりあっとじゃねぇよ", "description": "「わっしょいらりあっと」を発言する。"},
    "good_reaction": {"name": "いいね", "description": "発言に👍のリアクションをする。"},
    "eat_rice": {"name": "飯を食え、飯を", "description": "飯テロchで画像を送信する。"},
    "before_after": {"name": "悲劇的ビフォーアフター", "description": "「解体」と発言する。"},
    "cv_unimpl": {"name": "CV未実装", "description": "2名以上いるVCで2時間ミュート状態でいる。"},
    "everyone_8pm": {"name": "8時だョ！全員集合", "description": "土曜日20時ちょうどにVCに6人以上入っている状態の場合付与。"},
    "dont_run": {"name": "逃げるな", "description": "「ノーツが抜けた」と発言する。"},
    "what_diary": {"name": "どんな日記だよ", "description": "特定のテキストを含むメッセージを送信する。"},
    "public_washer": {"name": "公認洗濯機", "description": "「maimai」を含むテキストを送信。"},
    "maimai_q": {"name": "maimai?", "description": "「洗濯機」を含むテキストを送信。"},
    "gekichumai": {"name": "ゲキチュウマイ！！！", "description": "「オンゲキ」「CHUNITHM」「maimai」のいずれかを含むテキストを送信。"},
    "ojou_janai": {"name": "お嬢じゃないなり", "description": "「お嬢」「ゆーと姫」のどちらかを含むテキストを送信。"},
    "folern": {"name": "folern", "description": "「コンスィーヤ」を含むテキストを送信。"},
    "happy_birthday": {"name": "Happybirthday!!!!", "description": "「誕生日」を含むテキストを送信。"},
    "buy_anger_2": {"name": "だから怒りを買うよって", "description": "「玄米」を含むテキストを送信。"},
    "cockroach": {"name": "いやあああぁぁぁぁぁぁぁ", "description": "「ゴキブリ」を含むテキストを送信。"},
    "sleep_early": {"name": "さっさと寝る", "description": "「ねむい」と24時間以内に5回言う。"},
    "louder": {"name": "もっと大きな声で！", "description": "-#で始まる文章を3回送る。"},
    "english_pro": {"name": "英語ペラペラ？", "description": "英数字および半角記号のみで構成された50文字以上の文章を送る。"},
    "ghost_story": {"name": "怪談は夏にお願いします", "description": "名前に「八尺」が含まれた状態で特定のメッセージを送る。"},
    "dice_hate": {"name": "僕らはダイスに嫌われている", "description": "ダイスでファンブル(96〜100)を2回連続で出す。"},
    "trash_same": {"name": "ゴミも同然♪", "description": "「無能」と言う。"},


    # ── 隠し実績 ──
     "black_history": {"name": "黒歴史", "description": "1分以内に3回自分の発言したメッセージを消す。", "is_hidden": True},
     "you_lose": {"name": "負けました", "description": "隠し実績を含む全ての実績を解除する。", "is_hidden": True},
     "all_unlock_q": {"name": "全実績解除？", "description": "隠し実績以外の実績を全部解除する。", "is_hidden": True},
    }